# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 325)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 531, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_titulo_conteo_puntos = QtWidgets.QLabel(self.frame)
        self.label_titulo_conteo_puntos.setGeometry(QtCore.QRect(0, 0, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_titulo_conteo_puntos.setFont(font)
        self.label_titulo_conteo_puntos.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(114, 159, 207);")
        self.label_titulo_conteo_puntos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_conteo_puntos.setObjectName("label_titulo_conteo_puntos")
        self.boton_siguiente = QtWidgets.QPushButton(self.frame)
        self.boton_siguiente.setGeometry(QtCore.QRect(50, 240, 191, 25))
        self.boton_siguiente.setObjectName("boton_siguiente")
        self.tabla_anterior = QtWidgets.QTableWidget(self.frame)
        self.tabla_anterior.setGeometry(QtCore.QRect(270, 80, 211, 192))
        self.tabla_anterior.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_anterior.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_anterior.setObjectName("tabla_anterior")
        self.tabla_anterior.setColumnCount(2)
        self.tabla_anterior.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_anterior.setItem(5, 1, item)
        self.tabla_anterior.horizontalHeader().setVisible(True)
        self.tabla_anterior.horizontalHeader().setDefaultSectionSize(105)
        self.tabla_anterior.verticalHeader().setVisible(False)
        self.tabla_anterior.verticalHeader().setDefaultSectionSize(29)
        self.splitter_7 = QtWidgets.QSplitter(self.frame)
        self.splitter_7.setGeometry(QtCore.QRect(50, 80, 191, 149))
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_mineral = QtWidgets.QLabel(self.splitter_4)
        self.label_mineral.setObjectName("label_mineral")
        self.label_size = QtWidgets.QLabel(self.splitter_4)
        self.label_size.setObjectName("label_size")
        self.label_redon = QtWidgets.QLabel(self.splitter_4)
        self.label_redon.setObjectName("label_redon")
        self.label_esfer = QtWidgets.QLabel(self.splitter_4)
        self.label_esfer.setObjectName("label_esfer")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.input_mineral = QtWidgets.QLineEdit(self.splitter_5)
        self.input_mineral.setObjectName("input_mineral")
        self.input_size = QtWidgets.QSpinBox(self.splitter_5)
        self.input_size.setObjectName("input_size")
        self.input_redon = QtWidgets.QSpinBox(self.splitter_5)
        self.input_redon.setObjectName("input_redon")
        self.input_esfer = QtWidgets.QSpinBox(self.splitter_5)
        self.input_esfer.setObjectName("input_esfer")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_coor_y = QtWidgets.QLabel(self.splitter_2)
        self.label_coor_y.setObjectName("label_coor_y")
        self.input_coor_y = QtWidgets.QSpinBox(self.splitter_2)
        self.input_coor_y.setObjectName("input_coor_y")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_coor_x = QtWidgets.QLabel(self.splitter)
        self.label_coor_x.setObjectName("label_coor_x")
        self.input_coor_x = QtWidgets.QSpinBox(self.splitter)
        self.input_coor_x.setObjectName("input_coor_x")
        self.splitter_8 = QtWidgets.QSplitter(self.frame)
        self.splitter_8.setGeometry(QtCore.QRect(290, 40, 191, 21))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_censo = QtWidgets.QLabel(self.splitter_8)
        self.label_censo.setObjectName("label_censo")
        self.output_censo = QtWidgets.QLCDNumber(self.splitter_8)
        self.output_censo.setObjectName("output_censo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo_conteo_puntos.setText(_translate("MainWindow", "Conteo de Puntos"))
        self.boton_siguiente.setText(_translate("MainWindow", "Siguiente"))
        item = self.tabla_anterior.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabla_anterior.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tabla_anterior.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tabla_anterior.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tabla_anterior.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tabla_anterior.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tabla_anterior.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Propiedad"))
        item = self.tabla_anterior.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Valor"))
        __sortingEnabled = self.tabla_anterior.isSortingEnabled()
        self.tabla_anterior.setSortingEnabled(False)
        item = self.tabla_anterior.item(0, 0)
        item.setText(_translate("MainWindow", "Mineral"))
        item = self.tabla_anterior.item(1, 0)
        item.setText(_translate("MainWindow", "Tamaño"))
        item = self.tabla_anterior.item(2, 0)
        item.setText(_translate("MainWindow", "Redondez"))
        item = self.tabla_anterior.item(3, 0)
        item.setText(_translate("MainWindow", "Esfericidad"))
        item = self.tabla_anterior.item(4, 0)
        item.setText(_translate("MainWindow", "Coor X:"))
        item = self.tabla_anterior.item(5, 0)
        item.setText(_translate("MainWindow", "Coor Y:"))
        self.tabla_anterior.setSortingEnabled(__sortingEnabled)
        self.label_mineral.setText(_translate("MainWindow", "Mineral"))
        self.label_size.setText(_translate("MainWindow", "Tamaño"))
        self.label_redon.setText(_translate("MainWindow", "Redondez"))
        self.label_esfer.setText(_translate("MainWindow", "Esfericidad"))
        self.label_coor_y.setText(_translate("MainWindow", "Coordenada Y:"))
        self.label_coor_x.setText(_translate("MainWindow", "Coordenada X:"))
        self.label_censo.setText(_translate("MainWindow", "Puntos censados"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

